services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ${DOCKER_REGISTRY-}auth-server-frontend
    container_name: auth_server_frontend_container
    ports:
      - "4200:4200"
    restart: on-failure